### ISSUE TITLE
Client not properly handling 404 on removing incomingPhoneNumber

### ISSUE THREAD

**Issue by KaptainKrayola** [signalwire/signalwire-node#118]
calling `client.incomingPhoneNumbers(sid).remove()` on a sid for a number that isn't in your account throws an error `SyntaxError: Unexpected token N in JSON at position 0` seemingly because the client expects JSON back and isn't checking the HTTP status code (404 in this case) before trying to parse the JSON.

**Comment by KaptainKrayola** [comment]
Just saw it happen with a 422 HTTP Status code as well.  The headers say it's application/json but the body is empty.

```Server →nginx
Date →Wed, 19 Jun 2019 19:45:47 GMT
Content-Type →application/json
Transfer-Encoding →chunked
Connection →keep-alive
X-RateLimit-Limit →50000
X-RateLimit-Remaining →46406
X-RateLimit-Reset →1560974400
Cache-Control →no-cache
X-Request-Id →d61f00c5-cd96-4dcc-a795-b2f87c5da413
X-Runtime →0.255714
Strict-Transport-Security →max-age=15768000; includeSubDomains```

**Comment by edolix** [comment]
@KaptainKrayola what method did you use to receive 422 code?

I confirm the 404 is fixed and it now returns application/json header with this payload:

```
{
    "code": 20404,
    "message": "The requested resource was not found.",
    "more_info": "https://signalwire.com",
    "status": 404
}
```

**Comment by KaptainKrayola** [comment]
it's a DELETE operation and doesn't appear to be client related.  It's something on the SignalWire end with a particular number in my account.

**Comment by edolix** [comment]
Ok so always with `incomingPhoneNumbers(sid).remove()`. I'll get back to you ASAP

**Comment by bryanrite** [comment]
@KaptainKrayola We should be responding properly now on the DELETE operation as well. I'm going to close this issue, but feel free to reopen it if you have any more questions!
