### ISSUE TITLE
Wanted: Official Typescript typedef file (index.d.ts) for @signalwire/node

### ISSUE THREAD

**Issue by talgolan** [signalwire/signalwire-node#119]
Given the fact that this module is written in Typescript, would it be possible to have an official Typescript typedef file (index.d.ts) created?

As a Typescript developer, it sure would be great to have an official typedef included.

Here is a scaffold I created via dts-gen. Needless to say, if I could roll this typedef myself, I gladly would. Unfortunately, I do not have the chops.

/** Declaration file generated by dts-gen */
declare module "@signalwire/node" {
  export class RelayClient {
    constructor(...args: any[]);

    connect(...args: any[]): void;

    static off(...args: any[]): void;

    static on(...args: any[]): void;

    static uuid(...args: any[]): void;
  }

  export function RestClient(username: any, token: any, opts: any): any;

  export namespace RestClient {
    class Twilio {
      constructor(username: any, password: any, opts: any);

      request(opts: any): any;

      validateSslCert(): any;
    }

    function IpMessagingClient(sid: any, tkn: any, options: any): void;

    function LookupsClient(sid: any, tkn: any, options: any): void;

    function MonitorClient(sid: any, tkn: any, options: any): void;

    function PricingClient(sid: any, tkn: any, options: any): void;

    function RestClient(sid: any, tkn: any, options: any): void;

    function TaskRouterClient(sid: any, tkn: any, options: any): void;

    function TrunkingClient(sid: any, tkn: any, options: any): void;

    function validateExpressRequest(
      request: any,
      authToken: any,
      opts: any
    ): any;

    function validateRequest(
      authToken: any,
      twilioHeader: any,
      url: any,
      params: any
    ): any;

    function validateRequestWithBody(
      authToken: any,
      twilioHeader: any,
      requestUrl: any,
      body: any
    ): any;

    function webhook(...args: any[]): any;

    namespace LaML {
      class FaxResponse {
        constructor();

        receive(attributes: any): any;

        reject(attributes: any): any;
      }

      class MessagingResponse {
        constructor();

        message(attributes: any, body: any): any;

        redirect(attributes: any, url: any): any;
      }

      class VoiceResponse {
        constructor();

        connect(attributes: any): any;

        dial(attributes: any, number: any): any;

        echo(attributes: any): any;

        enqueue(attributes: any, name: any): any;

        gather(attributes: any): any;

        hangup(attributes: any): any;

        leave(attributes: any): any;

        pause(attributes: any): any;

        pay(attributes: any): any;

        play(attributes: any, url: any): any;

        prompt(attributes: any): any;

        queue(attributes: any, name: any): any;

        record(attributes: any): any;

        redirect(attributes: any, url: any): any;

        reject(attributes: any): any;

        say(attributes: any, message: any): any;

        sms(attributes: any, message: any): any;
      }
    }

    namespace jwt {
      class AccessToken {
        constructor(accountSid: any, keySid: any, secret: any, options: any);

        addGrant(grant: any): void;

        toJwt(algorithm: any): any;

        static ALGORITHMS: string[];

        static DEFAULT_ALGORITHM: string;
      }

      class ClientCapability {
        constructor(options: any);

        addScope(scope: any): void;

        toJwt(): any;
      }

      namespace AccessToken {
        class ChatGrant {
          constructor(options: any);

          toPayload(): any;
        }

        class ConversationsGrant {
          constructor(options: any);

          toPayload(): any;
        }

        class IpMessagingGrant {
          constructor(options: any);
        }

        class SyncGrant {
          constructor(options: any);

          toPayload(): any;
        }

        class TaskRouterGrant {
          constructor(options: any);

          toPayload(): any;
        }

        class VideoGrant {
          constructor(options: any);

          toPayload(): any;
        }

        class VoiceGrant {
          constructor(options: any);

          toPayload(): any;
        }
      }

      namespace ClientCapability {
        class EventStreamScope {
          constructor(filters: any);

          payload(): any;
        }

        class IncomingClientScope {
          constructor(clientName: any);

          payload(): any;
        }

        class OutgoingClientScope {
          constructor(options: any);

          payload(): any;
        }
      }

      namespace taskrouter {
        class TaskRouterCapability {
          constructor(options: any);

          addPolicy(policy: any): void;

          toJwt(): any;

          static Policy: any;
        }

        namespace util {
          // Too-deep object hierarchy from signalwire__node.RestClient.jwt.taskrouter.util
          const activitiesUrl: any;

          // Too-deep object hierarchy from signalwire__node.RestClient.jwt.taskrouter.util
          const defaultEventBridgePolicies: any;

          // Too-deep object hierarchy from signalwire__node.RestClient.jwt.taskrouter.util
          const defaultWorkerPolicies: any;

          // Too-deep object hierarchy from signalwire__node.RestClient.jwt.taskrouter.util
          const reservationsUrl: any;

          // Too-deep object hierarchy from signalwire__node.RestClient.jwt.taskrouter.util
          const taskQueuesUrl: any;

          // Too-deep object hierarchy from signalwire__node.RestClient.jwt.taskrouter.util
          const tasksUrl: any;

          // Too-deep object hierarchy from signalwire__node.RestClient.jwt.taskrouter.util
          const workersUrl: any;

          // Too-deep object hierarchy from signalwire__node.RestClient.jwt.taskrouter.util
          const workspacesUrl: any;
        }
      }
    }
  }
}

**Comment by edolix** [comment]
Hello @talgolan! Adding definition files to the packages is on the pipeline and will be released around next week.

**Comment by talgolan** [comment]
@edolix: This is fantastic news. I'm more than happy to beta test between now and next week. I'm actively working on an MPV and would love to be able to remove the '// @ts-ignore' statements. Let me know. Thank you.

**Comment by edolix** [comment]
@talgolan the `.d.ts` files will be available in `@signalwire/node` from the next version we're working on. 👍
