### ISSUE TITLE
API Endpoints No Longer Working

### ISSUE THREAD

**Issue by cpetrosi** [signalwire/signalwire-node#12]
examples in the following sections don’t seem to be working anymore:
- available phone numbers
- incoming phone numbers
- queues
- queue members
- recordings
- recording transcriptions

**Comment by bryanrite** [comment]
These endpoints are no longer working, someone on the message board indicated that they required adding `.api` to the client line to make it work, like: 

`client.api.availablePhoneNumbers('US')` 

rather than our documented (and twilio compatible): 

`client.availablePhoneNumbers('US')`

**Comment by bryanrite** [comment]
Looks like a versioning issue, still investigating.

**Comment by bryanrite** [comment]
I'm going to close as this looks like a non-issue.
