### ISSUE TITLE
getting requestor_nodeif error now even after reload

### ISSUE THREAD

**Issue by muteesa** [signalwire/signalwire-node#139]
my relay-native vanilla example is now broken even after reload. I get the error below.
 this eror comes after the status has changed to connected.. and it was working before.

![image](https://user-images.githubusercontent.com/2539239/61136800-e98b1280-a4cc-11e9-9855-48e8a404b082.png)

**Comment by edolix** [comment]
@muteesa is the JWT for auth still valid?

**Comment by muteesa** [comment]
having talked to edoardo, I generated a new jwt in a new project and my app worked again without this error. Edoardo is investigating the casue of this. even new jwt's is old project were not working.
