### ISSUE TITLE
Error on getting list of available phone numbers

### ISSUE THREAD

**Issue by baymaxdev** [signalwire/signalwire-node#157]
When I tried to get the list of available numbers which contain "2", the API returns following error.
```
{
    "status": 422,
    "message": "Contains invalid format -- we do not support '*' wildcard yet.",
    "code": "90000",
    "moreInfo": "https://signalwire.com"
}
```
This only happens when containing phone number length is one.
However, when I searched on Signalwire dashboard it returns phone numbers correctly.
What is going wrong here?

**Comment by edolix** [comment]
Hi @baymaxdev, i'm looking at this issue. Please, can you share a snippet to reproduce it?

Are you using `Contains` to filter the number?

Ref: https://docs.signalwire.com/topics/laml-api/#api-reference-available-phone-numbers-search-for-local-availablephonenumbers

**Comment by baymaxdev** [comment]
@edolix Yes, I am using contains. Here is code snippet
```
const { RestClient } = require('@signalwire/node');
const client = new RestClient(
  process.env.SIGNALWIRE_PROJECT_ID,
  process.env.SIGNALWIRE_API_TOKEN,
  {
    signalwireSpaceUrl: process.env.SIGNALWIRE_SPACE_URL
  }
);
...
...
numbers = await client.availablePhoneNumbers('US')
      .tollFree.list({
        areaCode,
        contains: key || ''
      })
```

**Comment by edolix** [comment]
Ok, got it. Thanks! 
I'll let you know ASAP 👍

**Comment by bryanrite** [comment]
This is fixed now @baymaxdev, no need to update your client, it was a server side issue. Thanks for the feedback!
