### ISSUE TITLE
Messaging scope seems to still be using "calling"

### ISSUE THREAD

**Issue by lpradovera** [signalwire/signalwire-node#158]
Steps to Reproduce:

Log onto SignalWire Dashboard
Click “Create an API Token
Click New on API Credentials Screen
Enter a new name for the API Token.
Within Relay Scopes ensure ONLY Messaging is selected, Calling needs to be unselected.
Create the source file below “basic_test.js”
Run basic
 

Source Code to Reproduce:
```node
// basic_test.js

const { RelayConsumer } = require('@signalwire/node')

const consumer = new RelayConsumer({

  project: 'XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX',

  token: 'PTXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',

  contexts: ['default'],

  onIncomingMessage: async (message) => {

    // Handle the inbound message here..

    console.log('Received message', message.id, message.context);

  }

})

consumer.run()
```

Error:
$ node basic_test.js

2019-08-12 18:49:21.065 - Session Ready!

2019-08-12 18:49:21.114 - Error registering contexts: [-32003] The scopes for this authorization do not permit the use of calling

(node:38927) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'message' of undefined

    at Object.<anonymous> (/Users/cc3094/node_modules/@signalwire/node/dist/common/src/services/Receive.js:35:36)

    at Generator.next (<anonymous>)

    at fulfilled (/Users/cc3094/node_modules/@signalwire/node/dist/common/src/services/Receive.js:4:58)

    at process._tickCallback (internal/process/next_tick.js:68:7)

(node:38927) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

(node:38927) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by lpradovera** [comment]
This issue was brought up to me at ClueCon. Let me know if I can help, @edolix .

**Comment by bryanrite** [comment]
This is an issue with permissions checking on the underlying Relay network. We are releasing a fix for this soon.

**Comment by bryanrite** [comment]
This should be fixed in production, @lpradovera can you verify?

**Comment by edolix** [comment]
@bryanrite this is fixed. I'll open another issue to better handle the server response in case of error.
