### ISSUE TITLE
Error calling tap with websocket source

### ISSUE THREAD

**Issue by feynmanliang** [signalwire/signalwire-node#165]
Calling `Call#tap` with `device.type == 'ws'` results in an error. The websocket endpoint is never hit.

Expected behavior: a websocket connection is established to the provided `device.uri`

Actual behavior: an error with message "Relay command failed with code: -32602 - Invalid CallTapParams"

Minimal repro example
```
import { RelayConsumer } from '@signalwire/node';

const consumer = new RelayConsumer({
  project: 'XXX',
  token: 'XXX',
  contexts: ['default'],

  onIncomingCall: async (call:any) => {
    const { successful  } = await call.answer()
    if (!successful) { return }

    const tap = { type: 'audio'  }
    const device = { type: 'ws', uri: 'ws://82776d6a.ngrok.io'}
    const tapResult = await call.tap(tap, device)
    if (tapResult.successful) {
      const { sourceDevice, destinationDevice  } = tapResult
      console.log(sourceDevice)
      console.log(destinationDevice)
    }
  }

})

consumer.run()
```

Console output
```
❮ ts-node main.ts                                          
2019-08-22 18:57:08.822 - Session Ready!
2019-08-22 18:57:08.870 - Receiving all inbound related to the requested relay contexts
2019-08-22 19:01:44.963 - Relay command failed with code: -32602 - Invalid CallTapParams
```

**Comment by edolix** [comment]
Hi @feynmanliang, the `device.type == ws` is not supported yet. 
There was an issue in our [Call#tap documentation](https://docs.signalwire.com/topics/relay-sdk-nodejs/v2/#api-reference-relay-calling-call-methods-tap) that we updated thanks to your feedback!

You can use `tap` with `rtp`.

Thanks again.
