### ISSUE TITLE
browser to phone Call  

### ISSUE THREAD

**Issue by cooldeeparmar** [signalwire/signalwire-node#180]
Hello 
how to set specific number for caller id  there are only one parameter for create new call "destinationNumber".
  const params = {
        destinationNumber: document.getElementById('number').value, // required!
        audio: document.getElementById('audio').checked,
        video: document.getElementById('video').checked ? { aspectRatio: 16/9 } : false,
      };
      currentCall = client.newCall(params);

there are caller id set randomly please help me how to set from number in new call function

**Comment by edolix** [comment]
Hi @cooldeeparmar! Set the caller id in the JS SDK is not supported yet. We're working on it and will be released soon!

**Comment by bryanrite** [comment]
@cooldeeparmar You can specify `callerNumber` when making a new call, and it will properly set the caller ID when dialling a phone number. Thanks for the suggestion!

**Comment by cooldeeparmar** [comment]
Thank you for your reply
