### ISSUE TITLE
stuck when: npm run setup js

### ISSUE THREAD

**Issue by pouledodue** [signalwire/signalwire-node#228]
Hi is normal it is quite stuck on the nice indicator?

```
➜  signalwire-node npm run setup js

  ✔ Setup @signalwire/common
  ❯ Setup @signalwire/js
    ⠼ install npm deps, lint source code, run tests and make a clean build...
```

Can I be sure it completed successfully if I kill it?

**Comment by edolix** [comment]
Hi @pouledodue! 
Since `npm run setup js` just install all the dependencies, check the code with linter and jest and then build the bundled version... it depends mainly on the network speed (to download deps from NPM) and your machine performance to pass the test/build phases.

> Can I be sure it completed successfully if I kill it?

No, you should wait the process to complete

**Comment by pouledodue** [comment]
15 minutes and still running, normal?

**Comment by edolix** [comment]
Absolutely not normal. Can you kill and retry it?

**Comment by pouledodue** [comment]
retried multiple times, indicator keeps turning
it does something, as I hear the fan ramping up a bit but the indicator turns eternally

**Comment by edolix** [comment]
Let's try this from the root of the repo:

```
npm install
cd packages/js
npm install
```

After these command you can run `npm run build` from `packages/js` folder to build the package.

**Comment by pouledodue** [comment]
thanks, worked
Its probably just the fancy indicator library that get stuck for some reason

**Comment by edolix** [comment]
I don't think it's an issue with the indicator.
The `setup` command do - in addition of `build`:

```
npm run tslint
npm run test
```
Always into `packages/js`. 
Let me know how it goes with those or share here your Node/NPM versions and OS specs so i can dig a bit 👍

**Comment by pouledodue** [comment]
stuck on: 
```
jest --forceExit --detectOpenHandles
```

jest 25.1.0
node v12.10.0
npm 6.13.7

macOS Catalina 10.15.3

**Comment by edolix** [comment]
Ok thanks. It seems an issue with Jest on the latest npm release. 
I'll figure it out 👍
