### ISSUE TITLE
Calling signalwire phone number not prompting listener notification 

### ISSUE THREAD

**Issue by Nashid95** [signalwire/signalwire-node#230]
I followed your instructions to set up this application to test it out on react native using your vanillaexample.

I was able to run the application and used a JWT that I generated through postman for the time being.

I was able to call out from the react native app running on android studio and the call went through good. But then I tried calling back and it's just dead silence. I see the call in signal wire on the activity log but the relay client does not seem to budge that there's an incoming call.

I'm not sure if my phone number is set up correctly.

I set up the phone number to user Relay as the handler because I assumed that's what it needs to be but I have no idea what to put in the Context field.

**Comment by edolix** [comment]
Hi @Nashid95! 
You should set the phone number as `a Verto/WebRTC Endpoint` with a `resource` name you  want.
Then you should get a JWT using the same `resource` name - See the resource parameter in [Creating Tokens](https://docs.signalwire.com/topics/relay-sdk-jwt-auth/#authentication-using-jwt-creating-tokens) section.

With the new JWT and the phone number pointed to the resource name, you will be able to reach your your react-native application.

**Comment by Nashid95** [comment]
Gotcha, so when using React Native, the call handler needs to be verto/webrtc end point.

So I went to the same cantina.signalwire.com (which I have a feeling I'm doing the setting up webrtc endpoint completey wrong) and i logged in there and then I set up user/credential 
![image](https://user-images.githubusercontent.com/22968062/75998158-a0555c00-5ebd-11ea-8605-5a34aa64a849.png)

and i used those on my client.iceServers set up. But what do you I put in the endpoint field? 

talking about the field below.
![example](https://user-images.githubusercontent.com/22968062/75997949-57050c80-5ebd-11ea-8d8a-909ee774d0e3.png)


Another Issue that is occuring is this error - Running Android Studio using your example, The only difference is that I moved my setup of the client from Constructor to componentDidMount and maybe that's not possible to do but I figured I needed to be there to call backend and get JWT/refresh token.

Here's the error {requester_nodeid: "ba4d8366-8b38-43c4-ad9d-41e491332a75", responder_nodeid: "3c976eca-5b57-424b-b87d-f3029a1b9eff", code: -32003, message: "Requester validation failed"}

**Comment by edolix** [comment]
@Nashid95 you don't need `cantina.signalwire.com` to run your RN application.
Instead, the `Requester validation failed` could happen because you're using an invalid/expired/missing JWT?

When are you getting that error?
Were you be able to receive an inbound call on Android?

**Comment by Nashid95** [comment]
Okay then I'm really confused. What is the the point in setting up in iceServers to connect to the cantina in the example of vanilla.

- So where/how do i decided what to put the field above for call webrtc call handler? (does this not relate to that cantina thing)


- The only way to NOT get this error is wipe data on the emulator then rerun it and run react-native run-android, the inital load works good i can call out  but if i refresh or restart that error starts happening. Here is my app.js file below.

Again I'm not able to do any inbound I'm not sure how to set it up to receive it in the relay. If i set up my phone number to point webrtc endpoint the phone call says it's not reachable when i call. 

import React, { Component } from 'react';
import { TouchableOpacity, StyleSheet, Text, View, TextInput, KeyboardAvoidingView, Alert } from 'react-native';
import Icon from 'react-native-vector-icons/MaterialCommunityIcons';
import { Relay } from '@signalwire/react-native';
import { RTCView } from 'react-native-webrtc';
import Colors from './Colors';
export default class App extends Component {
  constructor(props) {
    super(props)
    this.makeCall = this.makeCall.bind(this)
    this.hangup = this.hangup.bind(this)
    this.toggleMic = this.toggleMic.bind(this)
    this.toggleCam = this.toggleCam.bind(this)
    this.toggleDeaf = this.toggleDeaf.bind(this)
    this.switchCamera = this.switchCamera.bind(this)
    this.toggleSpeaker = this.toggleSpeaker.bind(this)
    this.state = {
      connected: false,
      call: null,
      extension: '3593',
      btnMicActive: true,
      btnDeafActive: true,
      btnCamActive: true,
      btnSpeakerActive: true
    }
    this.client = undefined;
  }
  async componentDidMount() {
    try {
      let jwt = await this.generateJWT();
      
      // Use your Project ID and a JWT to create a Relay client.
      this.client = new Relay({
        project: '9bba4aea-47b0-4bcc-b4ab-d266ccec361b',
        token: jwt.jwt_token
      })
      this.client.on('signalwire.ready', () => {
        this.setState({ connected: true })
      })
      this.client.on('signalwire.error', (error) => {
        console.error(error)
      })
      this.client.on('signalwire.notification', async (notification) => {
        console.log(notification);
        switch (notification.type) {
          case 'callUpdate':
            return this._handleCallUpdate(notification.call)
          case 'refreshToken':
            const refreshToken = await this.refreshJWT(jwt.refresh_token);
            this.client.refreshToken(refreshToken.jwt_token);
        }
      })
      this.client.iceServers = [{
        url: 'turn:turn.cantina.signalwire.com:1995?transport=tcp',
        username: 'nbainy',
        credential: 'nbainy1'
      }];
      this.client.on('signalwire.socket.open', () => {
        console.log('Socket Open')
      })
      this.client.on('signalwire.socket.close', (event) => {
        console.log('Socket Close', event)
      })
      this.client.on('signalwire.socket.error', () => {
        console.log('Socket Error')
      })
      await this.client.connect();
    }
    catch (ex) {
      console.log(ex);
    }
  }
  generateJWT = () => {
    return fetch("https://domain.signalwire.com/api/relay/rest/jwt", {
      headers: {
        Authorization: "Basic [MYBASE64 projectId:token]",
        "Content-Type": "application/json"
      },
      method: "POST"
    }).then((response) => {
      return response.json();
    }).catch(err => console.log(err));
  }
  refreshJWT = (refreshToken) => {
    return fetch("https://domain.signalwire.com/api/relay/rest/jwt", {
      headers: {
        Authorization: "Basic [MYBASE64 projectId:token]",
        "Content-Type": "application/json"
      },
      method: "PUT",
      body: {"refresh_token": refreshToken}
    }).then((response) => {
      return response.json();
    }).catch(err => console.log(err));
  }
  makeCall() {
    this.client.newCall({ destinationNumber: this.state.extension, audio: true })
  }
  hangup() {
    this.state.call.hangup()
  }
  toggleMic() {
    this.setState({ btnMicActive: !this.state.btnMicActive })
    this.state.call.toggleAudioMute()
  }
  toggleCam() {
    this.setState({ btnCamActive: !this.state.btnCamActive })
    this.state.call.toggleVideoMute()
  }
  toggleDeaf() {
    this.setState({ btnDeafActive: !this.state.btnDeafActive })
    this.state.call.toggleDeaf()
  }
  switchCamera() {
    this.state.call.switchCamera()
  }
  toggleSpeaker() {
    this.setState({ btnSpeakerActive: !this.state.btnSpeakerActive }, () => {
      this.state.call.setSpeakerPhone(this.state.btnSpeakerActive)
    })
  }
  _handleCallUpdate(call) {
    switch (call.state) {
      case 'ringing': {
        const { remoteCallerName, remoteCallerNumber } = call.options
        const caller = remoteCallerName || remoteCallerNumber
        Alert.alert('Inbound Call', `Call from ${caller}`,
          [
            {
              text: 'Reject',
              onPress: () => call.hangup(),
              style: 'cancel'
            },
            {
              text: 'Answer',
              onPress: () => call.answer()
            }
          ],
          { cancelable: false }
        );
        break
      }
      case 'active':
        this.setState({ call })
        break
      case 'destroy':
        this.setState({ call: null })
        break
    }
  }
  _status() {
    return this.state.connected ? 'Connected' : 'Disconnected'
  }
  _middle() {
    if (this.state.call) {
      let streamURL = null
      const { options: { remoteStream = null, localStream = null } } = this.state.call
      console.log('localStream', localStream, localStream.toURL())
      if (remoteStream) {
        console.log('remoteStream', remoteStream, remoteStream.toURL())
        streamURL = remoteStream.toURL()
      }
      return (
        <View style={styles.wrapperMiddle}>
          {streamURL && <RTCView mirror={false} objectFit='contain' streamURL={streamURL} style={{ width: '100%', height: '100%' }} zOrder={1} />}
        </View>
      )
    } else {
      return (
        <View style={styles.wrapperMiddle}>
          <Text style={styles.instructions}>Enter a number:</Text>
          <TextInput
            style={styles.textInput}
            textAlign={'center'}
            onChangeText={(extension) => this.setState({ extension })}
            value={this.state.extension}
          />
        </View>
      )
    }
  }
  _bottom() {
    if (this.state.call) {
      return (
        <View style={styles.wrapperBottom}>
          <View style={styles.wrapperBottomRow}>
            <TouchableOpacity style={styles.button} onPress={this.toggleMic}>
              <Icon name='microphone' size={25} color={this.state.btnMicActive ? '#000' : 'gray'} />
              <Text style={styles.buttonText}>Mute</Text>
            </TouchableOpacity>
            <TouchableOpacity style={styles.button} onPress={this.toggleDeaf}>
              <Icon name='volume-mute' size={25} color={this.state.btnDeafActive ? '#000' : 'gray'} />
              <Text style={styles.buttonText}>Deaf</Text>
            </TouchableOpacity>
            <TouchableOpacity style={styles.button} onPress={this.toggleCam}>
              <Icon name='camera' size={25} color={this.state.btnCamActive ? '#000' : 'gray'} />
              <Text style={styles.buttonText}>Camera</Text>
            </TouchableOpacity>
            <TouchableOpacity style={styles.button} onPress={this.switchCamera}>
              <Icon name='camera-retake' size={25} color='#000' />
              <Text style={styles.buttonText}>Flip Cam</Text>
            </TouchableOpacity>
            <TouchableOpacity style={styles.button} onPress={this.toggleSpeaker}>
              <Icon name='volume-high' size={25} color={this.state.btnSpeakerActive ? '#000' : 'gray'} />
              <Text style={styles.buttonText}>Speaker</Text>
            </TouchableOpacity>
          </View>
          <View style={styles.wrapperBottomRow}>
            <TouchableOpacity style={[styles.button, { backgroundColor: Colors.red }]} onPress={this.hangup}>
              <Icon name='phone-hangup' size={25} color='#FFF' />
            </TouchableOpacity>
          </View>
        </View>
      )
    } else {
      return (
        <View style={styles.wrapperBottom}>
          <View style={styles.wrapperBottomRow}>
            <TouchableOpacity style={[styles.button, { backgroundColor: Colors.green }]} onPress={this.makeCall}>
              <Icon name='phone' size={25} color='#FFFFFF' />
            </TouchableOpacity>
          </View>
        </View>
      )
    }
  }
  render() {
    return (
      <KeyboardAvoidingView style={styles.container}>
        <View style={styles.wrapperTop}>
          <Text style={styles.welcome}>Welcome to SignalWire!</Text>
          <Text style={styles.instructions}>Status: {this._status()}</Text>
        </View>
        {this._middle()}
        {this._bottom()}
      </KeyboardAvoidingView>
    );
  }
}
const styles = StyleSheet.create({
  container: {
    flex: 1
  },
  wrapperTop: {
    flex: 0.5,
    justifyContent: 'center'
  },
  wrapperMiddle: {
    flex: 2,
    justifyContent: 'center',
    alignItems: 'center',
    borderColor: '#000',
    borderTopWidth: 1
  },
  wrapperBottom: {
    flex: 0.5,
    borderColor: '#000',
    borderTopWidth: 1,
    borderBottomWidth: 1
  },
  wrapperBottomRow: {
    flex: 0.5,
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center'
  },
  textInput: {
    height: 40, width: '80%', borderColor: 'gray', borderWidth: 1,
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
  button: {
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 100,
    height: 40,
    width: '20%'
  },
  buttonText: {
    textAlign: 'center',
    fontSize: 12
  },
});

**Comment by edolix** [comment]
You can name the Verto/WebRTC endpoint with whatever you want. 
For example: 

1. enter the name `bob` in the field above and save
2. generate a JWT using `resource: 'bob'` as parameter. [Read here for details](https://docs.signalwire.com/topics/relay-sdk-jwt-auth/#authentication-using-jwt-creating-tokens)
3. connect your App using the new generated "bob JWT" and call the phone number. 

This way Relay will match the phone number with `bob` and will try to dial the endpoint using the `bob` JWT.

For the error after refresh: are you using the latest version? 

In addition: you should generate/refresh JWTs server-side **not client side**. This to avoid to publish your private space TOKEN.

Regarding iceServers: you're not connecting to cantina using iceServers. IceServers is a WebRTC thing to avoid NAT issues. 
Read more about ICE [here](https://developer.mozilla.org/en-US/docs/Web/API/RTCIceServer). I'll remove those from the repo since they are not necessary 👍

**Comment by Nashid95** [comment]
Cool. Thanks for explaining that about verto/webrtc.

I will try doing that later today and see if i can get inbound call.

Regarding the Error, latest version of what? 

I cloned your repo and went into the vanillaexample.
Here's my package.json

`{
  "name": "VanillaCalling",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest"
  },
  "dependencies": {
    "@react-native-community/async-storage": "^1.8.1",
    "@signalwire/react-native": "^1.0.0",
    "braces": ">=2.3.1",
    "mem": ">=4.0.0",
    "react": "16.8.3",
    "react-native": "0.59.9",
    "react-native-incall-manager": "^3.2.7",
    "react-native-vector-icons": "^6.6.0",
    "react-native-webrtc": "^1.75.3"
  },
  "devDependencies": {
    "@babel/core": "^7.5.4",
    "@babel/runtime": "^7.4.5",
    "babel-jest": "^24.8.0",
    "jest": "^24.8.0",
    "lodash": "4.17.14",
    "metro-react-native-babel-preset": "^0.54.1",
    "react-test-renderer": "16.8.3",
    "ws": ">=3.3.1"
  },
  "jest": {
    "preset": "react-native"
  }
}
`

I'm doing client side for now, I'm just starting with app. once it goes public  I will move it to server side.

**Comment by edolix** [comment]
Ok, double check the package-lock file to make sure you're running the latest version of [@signalwire/react-native](https://www.npmjs.com/package/@signalwire/react-native) 👍 

I'm going to close the issue, feel free to reopen it in case the inbound call will not work!
