### ISSUE TITLE
Update React Native and Trying to Use Expo.

### ISSUE THREAD

**Issue by Nashid95** [signalwire/signalwire-node#234]
Hey so I'm trying to make my debugging easier by using latest version expo and updating React native.

I managed to get all the packages configured correctly and linked the only issue with I run is that I'm getting this issue.

[@RNC/AsyncStorage]: NativeModule: AsyncStorage is null.

Any ideas what's going on?

Here's my package.json
```
{
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "web": "expo start --web",
    "start": "react-native start",
    "test": "jest"
  },
  "dependencies": {
    "@react-native-community/async-storage": "^1.8.1",
    "@signalwire/react-native": "^1.0.1",
    "braces": ">=2.3.1",
    "expo": "~36.0.0",
    "mem": ">=4.0.0",
    "react": "~16.9.0",
    "react-dom": "~16.9.0",
    "react-native": "~0.61.4",
    "react-native-incall-manager": "^3.2.7",
    "react-native-vector-icons": "^6.6.0",
    "react-native-webrtc": "^1.75.3"
  },
  "devDependencies": {
    "@babel/core": "^7.5.4",
    "babel-jest": "^24.8.0",
    "jest": "^24.8.0",
    "lodash": "4.17.14",
    "metro-react-native-babel-preset": "^0.54.1",
    "react-test-renderer": "~16.9.0",
    "ws": ">=3.3.1"
  },
  "jest": {
    "preset": "react-native"
  },
  "private": true
}
```

**Comment by edolix** [comment]
Hi @Nashid95 , this is not related to the SignalWire react-native package but instead on the `@react-native-community/async-storage` with Expo. 
I think you have to eject the App (so, not use Expo) to work with async-storage and react-native-webrtc.

**Comment by Nashid95** [comment]
So since expo currently does support webrtc. 
there's no way of using your sdk with Expo?

**Comment by edolix** [comment]
The [react-native-webrtc](https://github.com/react-native-webrtc/react-native-webrtc#react-native-webrtc) package doesn't support Expo. 

From the README: 

> NOTE for Expo users: this plugin doesn't work unless you eject.
