### ISSUE TITLE
after deploy not showing localhost

### ISSUE THREAD

**Issue by LinuxDevBD** [signalwire/signalwire-node#255]
Hello, I have used node js 10 and setup everything

> signalwire@0.0.1 setup /home/school/Downloads/signalwire-node
> node .scripts/setup.js "node"

  ✔ Setup @signalwire/common
  ✔ Setup @signalwire/node

Now how I can check this from localhost? I am using Ubuntu 18.04 Desktop
![Screenshot from 2020-07-12 17-49-54](https://user-images.githubusercontent.com/55578382/87245599-59c5ce80-c468-11ea-97ae-377e39286d64.png)

**Comment by edolix** [comment]
Hi @LinuxDevBD! Could you describe a bit more what are you trying to do, please?

From the description it looks like you are working with `signalwire-node` repository but this means you have to build the package you want (JS - Node.js or React Native) on your own. 
If you want to just using our SDKs you can start from [our documentation here](https://docs.signalwire.com/topics/relay/#relay-documentation-quickstart) where you will find the "Getting Started" for each language and platform. For example: NodeJS or React Native.

**Comment by LinuxDevBD** [comment]
I'm looking to integrated SignalWire integrate with Spoke using 
https://github.com/signalwire/signalwire-node
cd packages/js
npm install
npm run build
npm run tslint
npm run test

I was looking for signalwire-node GUI if any

**Comment by edolix** [comment]
@LinuxDevBD `signalwire-node` is a monorepo that contains 3 NPM packages: `@signalwire/js`, `@signalwire/node` and `@signalwire/react-native`. Each of these packages lets you integrare SignalWire services with - respectively - JS in the browser, NodeJS server and ReactNative.

I would recommend you to get started with our Nodejs SDK at this link: https://docs.signalwire.com/topics/relay-sdk-nodejs/v2/#relay-sdk-for-node-js
This way you will just use the package from NPM into your node project.


> I was looking for signalwire-node GUI if any

The SDK does not provide a GUI

**Comment by edolix** [comment]
@LinuxDevBD feel free to reopen if you have any other questions! 

Thanks
