### ISSUE TITLE
[Bug] Message response could not be received from messaging gateway

### ISSUE THREAD

**Issue by ankitjena** [signalwire/signalwire-node#263]
## Description
Trying to send a message to a number using the `RelayClient.messaging.send()` method throws the following error.
![image](https://user-images.githubusercontent.com/23580602/91259086-69387700-e78b-11ea-8334-71dcee5bf1fd.png)
The `client` is getting connected, I have checked this. Just the sending of message fails, I have tried other number as well with same result. I have looked around but cannot find any solution to this issue.

```ts
(async () => {
  await client.connect();
})();

export async function sendSms() {
  try {
    const sendResult = await client.messaging.send({
      context: "signup",
      from: SIGNALWIRE_PHONE_NUMBER,
      to: "+1‪6096300401",
      body: "Your OTP for sign in request at betterbank.app is"
    });
    return sendResult.successful
  } catch (error) {
    throw error;
  }
};
```

## Background
I have another server where I am using the `@signalwire/node` package for messaging too and it works perfectly fine(sending the message works and doesn't throw any error). 

Any help is appreciated. Thanks.

**Comment by edolix** [comment]
Hi @ankitjena! 

Is the other server running the same code? 
From the snippet above i can't see _how and when_ you use the `sendSms()` function.
If you can provide a running example i can see if there are any "client setup" issues. 

Also, you are using the raw client object without waiting for the `signalwire.ready` event: see [here](https://docs.signalwire.com/topics/relay-sdk-nodejs/v2/#api-reference-relay-client-methods-on) and [here](https://docs.signalwire.com/topics/relay-sdk-nodejs/v2/#api-reference-relay-client-events) for details.

Anyway - I will check if there are any issues with messaging and let you know, of course.

##### Suggestions
To avoid to deal with client setup I would suggest you to try out a Consumer instead:

- [Consumer docs](https://docs.signalwire.com/topics/relay-sdk-nodejs/v2/#api-reference-relay-consumer)
- [onTask](https://docs.signalwire.com/topics/relay-sdk-nodejs/v2/#api-reference-relay-consumer-event-handlers-ontask) and [Relay.Task](https://docs.signalwire.com/topics/relay-sdk-nodejs/v2/#api-reference-relay-task) to send jobs to your consumer.

Take a look at these examples to build a Consumer and send a "job" from another process:

[create-task.js](https://github.com/signalwire/signalwire-node/blob/master/packages/node/examples/calling/create-task.js)
[consumer.js](https://github.com/signalwire/signalwire-node/blob/master/packages/node/examples/calling/handle-tasks.js)

Thanks!

**Comment by ankitjena** [comment]
> Is the other server running the same code?

Yes exactly the same



> If you can provide a running example i can see if there are any "client setup" issues.

I am initializing the client when the server starts and the `sendSms` function is called when I actually call it from user's end(REST API in my case). I'll take a look at the `signalwire.ready` event but usually since I call connect on server start the client is connected( I get `true` from `client.connected` like I said).

Thanks for the suggestions. But if possible I would like to know what is causing this? Just curious since the same thing is working on another server. 

Thanks in advance.

**Comment by edolix** [comment]
> But if possible I would like to know what is causing this? Just curious since the same thing is working on another server.

Sure! 👍

**Comment by bryanrite** [comment]
@ankitjena Can I ask you to open a support ticket from your SignalWire account instead by visiting `https://<SPACE_NAME>.signalwire.com/support_tickets/new`? You can reference this Github issue in it, but the technical support staff will be able to assist you more and narrow down the issue, since the problem doesn't seem to be a technical SDK one, but something possibly with configuration or within the platform.

Thanks!

**Comment by ankitjena** [comment]
Thanks @bryanrite I'll do that

**Comment by ankitjena** [comment]
Hey @edolix , just curious about something else. You had suggested using consumer and task instead of raw client setup. But how do I access the client inside the `onTask` method of the consumer

**Comment by edolix** [comment]
@ankitjena you should be able to use the Consumer `client` property. See [the Consumer properties for details](https://docs.signalwire.com/topics/relay-sdk-nodejs/v2/#api-reference-relay-consumer-properties). 
Let me know how it goes!
