### ISSUE TITLE
How to connect SIP

### ISSUE THREAD

**Issue by MeghaPawar2410** [signalwire/signalwire-node#268]
I am able to get jet_token and my SIP information
But still not finding how I can connect my SIP to the server?

Can any one please help?

**Comment by edolix** [comment]
Hi @MeghaPawar2410! Can I ask you to open a support ticket from your SignalWire account instead by visiting `https://<SPACE_NAME>.signalwire.com/support_tickets/new` ? 
You can reference this Github issue in it, but the technical support staff will be able to assist you and reply to any other questions.

Feel free to reopen this or comment for any question - Thanks!
