### ISSUE TITLE
importing 'signalwire/react-native'

### ISSUE THREAD

**Issue by MeghaPawar2410** [signalwire/signalwire-node#269]
I want to use this:
import Relay from 'signalwire/react-native';

But facing following issue:
undefined unable to resolve module 'signalwire/react-native'

Can you please help in this?

**Comment by edolix** [comment]
Hi @MeghaPawar2410, you can follow the `Getting Started` and `Installation` section on our [official documentation here](https://docs.signalwire.com/topics/relay-sdk-react-native/v1/#relay-sdk-for-react-native).

Make sure to install `@signalwire/react-native` (with `@`) in a ReactNative application!

Also, can I ask you to open a support ticket from your SignalWire account by visiting https://<SPACE_NAME>.signalwire.com/support_tickets/new ?
You can reference this Github issue in it, but the technical support staff will be able to assist you and reply to any other questions related to our SDKs. 

Thanks!
