### ISSUE TITLE
SignalWire socket disconnect! Not able to again reconnect.

### ISSUE THREAD

**Issue by viv578ek** [signalwire/signalwire-node#274]
Hello Friends,

   I am connecting relay socket new Connection. I have to work perfectly. But after some time my JWT token expire. that case I  have refresh my token base one refresh_token value like 
Ex: 
 **curl https://your-space.signalwire.com/api/relay/rest/jwt \
  -X PUT \
  -u 'YourProjectID:YourProjectToken' \
  -H 'Content-Type: application/json' \
  -d '{
        "refresh_token": "XYZ"
      }'**

**I am getting New value save in Session storage 
{
    "jwt_token": "XYZ",
    "refresh_token": "ABC"
}**

And again Socket Connect with update jwt_token key-Value.But not able to connect again throw error : 
Socket Close {"code": 1000, "isTrusted": false, "reason": "Closed"}

Please Help me how we handle it issues for reconnect Socket.

Thanks 
Vivek Shukla

**Comment by edolix** [comment]
Hello @viv578ek! 

You can keep the session alive using the [refreshToken method](https://docs.signalwire.com/topics/relay-sdk-js/v1/#api-reference-relay-methods-refreshtoken). 
You have to refresh your token server-side and use it on the client following the example linked above.

**Comment by bryanrite** [comment]
I'm going to close this, as it is expected behaviour if the connection isn't updated with the new token and not a technical issue. @viv578ek Feel free to reach out to SignalWire support if you need further assistance!
