### ISSUE TITLE
[Bug] Task.deliver fails without throwing any error

### ISSUE THREAD

**Issue by ankitjena** [signalwire/signalwire-node#276]
## Background
We are using relay consumer and task to send smses. It was working perfectly fine previously, but today the task,deliiver fails without throwing any error. The error is `undefined`

The code looks something like this
```
//Consumer code
const consumer = new RelayConsumer({
  project: SIGNALWIRE_PROJECT_ID,
  token: SIGNALWIRE_PROJECT_TOKEN,
  contexts: ["sms"],
  onTask: async function(this: { client: RelayClient }, data: SmsTaskPayload) {
    try {
      const { context, to , body } = data;
      console.log("delivered");
      await this.client.messaging.send({
        context: "sms",
        from: SIGNALWIRE_PHONE_NUMBER,
        to: `+1${to}`,
        body
      });
    } catch (err) {
      throw err;
    }
  }
});

export const runRelayConsumer = () => {
  consumer.run();
};

//Task code
const relayTask = new Task(SIGNALWIRE_PROJECT_ID, SIGNALWIRE_PROJECT_TOKEN);

await relayTask.deliver("sms", {
      to,
      context: "sms",
      body: renderTemplate(body, context)
    });
```

## Bug
It is wrapped in a try catch and the error in catch comes out to be `undefined`. Though trying to send a message in consumer.ready method works properly. Not sure what's happening.

Help is appreciated. Thanks

**Comment by lpradovera** [comment]
Hello, just to clarify, the task does get delivered to the consumer then fails to send the message? Or is the failure in the relayTask.deliver API call?

**Comment by ankitjena** [comment]
The task doesn't get delivered to the consumer's onTask method. It fails on the deliver method and doesn't throw any error

**Comment by edolix** [comment]
Hello @ankitjena, i can see some issues in your code (eg: number of arguments for the onTask handler and the use of the private `this` keyword).

Can you try running this code? I've changed a bit the handlers to just logs the task but it should fix your issue.

> Consumer
```js
const { RelayConsumer } = require('@signalwire/node')

const consumer = new RelayConsumer({
  project: SIGNALWIRE_PROJECT_ID,
  token: SIGNALWIRE_PROJECT_TOKEN,
  contexts: ['sms'],
  ready: (consumer) => {
    // Consumer Ready..
  },
  onTask: async (message) => {
    console.log('TASK', message, consumer, consumer.client)
  }
})
console.log('Running', consumer.project, consumer.token)

consumer.run()
```

> Task
```js
const { Task } = require('@signalwire/node')

const yourTask = new Task(SIGNALWIRE_PROJECT_ID, SIGNALWIRE_PROJECT_TOKEN)
yourTask.deliver('sms', {
      to: 'example',
      context: 'sms',
      body: 'body here',
    })
```

Thanks!

**Comment by ankitjena** [comment]
@edolix I tried the above out. The task gets delivered but how do I access the client. It says the following
```
Property 'client' is protected and only accessible within class 'RelayConsumer' and it's subclass
```

**Comment by edolix** [comment]
@ankitjena you can use the `consumer.client` same as my example above:

```js
  onTask: async (message) => {
    console.log('TASK', message, consumer, consumer.client)
    // use "consumer.client" here
  }
```

`consumer` is declared at the global scope (with `const consumer = new RelayConsumer(...)`)

**Comment by ankitjena** [comment]
@edolix Thanks for helping out, we improved our code. But the bug was on the frontend side. Nevertheless thanks for all the help. It helped in debugging things better. Closing the ticket.

BTW the bug was phone number had special characters in it.
