### ISSUE TITLE
Cannot connect to any part of your api or get your node package working...

### ISSUE THREAD

**Issue by guyeatspants** [signalwire/signalwire-node#325]
Hey there!

For some odd reason i cannot connect to the relay client, rest, nor anything importing signalwire and putting in all my credentials.  Twilio for some reason throws an error, regarding a prompt that has already been declared, I've tried various changing the Twilio versions with no luck.

`
Identifier 'Prompt' has already been declared (960:9) in /Users/alex/Desktop/projects/***/node_modules/twilio/lib/twiml/VoiceResponse.js
958:  */
959: /* jshint ignore:end */
960: function Prompt(prompt) {
              ^
961:   this.prompt = prompt;
962:   this._propertyName = 'prompt';
`

I've imported it like so and have tried to initiate, same error no matter what.

i.e rest

>     import { RestClient } from '@signalwire/node'
>     
>     const signalwireClient = new RestClient('xxxxx-xxxx-xxxxx-xxxxx-xxxxxxxxx', 'xxxxxxxxxxx', { signalwireSpaceUrl: 'xxxxxxxx.signalwire.com' })
> 

If anyone has had this happen and figured it out, please help!

Thank you kindly.

**Comment by diagraphic** [comment]
Terns out I cannot import this.  It'll work as

> const { RestClient } = require('@signalwire/node') // no need to import

**Comment by edolix** [comment]
Hi @diagraphic! I'm not able to reproduce it, can you please share a reproducible example? Also, include the versions you are using please!

Here a very simple code that works with latest `@signalwire/node`:

```js
import { RestClient } from '@signalwire/node'

const client = new RestClient(
  '<Project-Id-Here>',
  '<Token-Here>',
  {
    signalwireSpaceUrl: '<Space-Url-Here>'
  }
)

client.messages.list()
  .then(list => {
    console.log(`You have ${list.length} messages.`)
  })
  .catch(console.error)
```

Thanks!
