### ISSUE TITLE
Error Installation

### ISSUE THREAD

**Issue by CoreLine76** [signalwire/signalwire-node#334]
Hello, why am I getting an error during installation? 
![hata](https://user-images.githubusercontent.com/92768020/152608622-dc1a8838-aeaf-41f2-a9d8-fb3dab1378ed.png)

**Comment by edolix** [comment]
Hey @CoreLine76 - from the screenshot i see you're using Windows. Any chance for you to give it a shot using the [WSL](https://docs.microsoft.com/en-us/windows/wsl/about)?

**Comment by edolix** [comment]
Closing due to lack of response - Feel free to reopen with more details. Thanks!
