### ISSUE TITLE
NPM reports high severity vulnerabilities due to dependence on vulnerable versions of twilio

### ISSUE THREAD

**Issue by waaronking** [signalwire/signalwire-node#367]
@signalwire/node is currently pinned on v3.29.2 of Twilio which was released on Mar 15, 2019. This version of Twilio was using MomentJS v2.19.3 which has documented vulnerabilites (see [https://security.snyk.io/package/npm/moment](https://security.snyk.io/package/npm/moment)). 

Doing a regular npm install today of @signalwire/node warns of "high severity vulnerabilities" due to the @signalwire/node pin to Twilio v3.29.2.

Updating pins to the latest version of Twilio (v3.83.0) resolves this issue. 

Updating will cause integration tests for fax related calls to fail, as fax support was ended by Twilio on December 17, 2021 (see [https://support.twilio.com/hc/en-us/articles/223136667-Fax-Support-on-Twilio](https://support.twilio.com/hc/en-us/articles/223136667-Fax-Support-on-Twilio)). The only other test that fails is an unused twilio import in `tests/relay/Calls.test.ts`.

**Comment by edolix** [comment]
[v2.5.1](https://www.npmjs.com/package/@signalwire/node/v/2.5.1) has been released with the last dependency version with Fax support.

**Comment by waaronking** [comment]
@edolix Thank you!
