### ISSUE TITLE
Resource is enforced in auth.

### ISSUE THREAD

**Issue by bryanrite** [signalwire/signalwire-node#98]
As discussed, resource and domain will be enforced in auth flow and Hagrid side. Can we remove this from web client and examples and coordinate with @Astaelan to make the necessary registrations in Hagrid are integrated upon connection.

**Comment by edolix** [comment]
@Astaelan i used domain and resource to `configure` the client after the protocol setup. With this change, will Hagrid cares about `configure` request?

**Comment by Astaelan** [comment]
I need to get more information about this. My understanding is that the resource may not be required to be provided in authorization, in which case there will be no resource to configure the endpoint with. Something is required to register the endpoint under with registrar (RE: configure), even if they can send out with any "from" based on not being present in the authorization.

I will need more information before we can make any decisions regarding the configure process.
